###
GET http://localhost:5000/api/activities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJib2IiLCJuYmYiOjE1NzczMjQ4NTksImV4cCI6MTU3NzkyOTY1OSwiaWF0IjoxNTc3MzI0ODU5fQ.aHiFJ0Ok4nXGD-kJNRxJWJCvIlghk6dd_N4lw8sfQEboxbYKZGBqqjQCU1A3Q6MCVpcr6FWPj_mp3pFg0mYKlg


### 
GET http://localhost:5000/api/activities/9a9ec76c-d2a6-48a4-9861-fe0ce5731d8b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJib2IiLCJuYmYiOjE1NzczMjQ4NTksImV4cCI6MTU3NzkyOTY1OSwiaWF0IjoxNTc3MzI0ODU5fQ.aHiFJ0Ok4nXGD-kJNRxJWJCvIlghk6dd_N4lw8sfQEboxbYKZGBqqjQCU1A3Q6MCVpcr6FWPj_mp3pFg0mYKlg

###
DELETE http://localhost:5000/api/activities/62607897-74f1-4dd7-9fda-e06957e14967
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJ0b20iLCJuYmYiOjE1Nzc0MDczNTAsImV4cCI6MTU3ODAxMjE1MCwiaWF0IjoxNTc3NDA3MzUwfQ.na71y5fwzi2DQvjgb7tHMUVNHrTxrpkv6A4l52QU5b5TrSIJuWZCsuThPmk7z0CmurIRlwmZs0rMXHtQws5ALw


###
GET http://localhost:5000/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJib2IiLCJuYmYiOjE1NzczMjQ4NTksImV4cCI6MTU3NzkyOTY1OSwiaWF0IjoxNTc3MzI0ODU5fQ.aHiFJ0Ok4nXGD-kJNRxJWJCvIlghk6dd_N4lw8sfQEboxbYKZGBqqjQCU1A3Q6MCVpcr6FWPj_mp3pFg0mYKlg

###
POST http://localhost:5000/api/activities/35e65508-9889-4885-9316-07b9d9d27b7b/attend
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJib2IiLCJuYmYiOjE1NzczMjQ4NTksImV4cCI6MTU3NzkyOTY1OSwiaWF0IjoxNTc3MzI0ODU5fQ.aHiFJ0Ok4nXGD-kJNRxJWJCvIlghk6dd_N4lw8sfQEboxbYKZGBqqjQCU1A3Q6MCVpcr6FWPj_mp3pFg0mYKlg


###
POST http://localhost:5000/api/activities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJib2IiLCJuYmYiOjE1NzczMjQ4NTksImV4cCI6MTU3NzkyOTY1OSwiaWF0IjoxNTc3MzI0ODU5fQ.aHiFJ0Ok4nXGD-kJNRxJWJCvIlghk6dd_N4lw8sfQEboxbYKZGBqqjQCU1A3Q6MCVpcr6FWPj_mp3pFg0mYKlg

{
    "title": "yourfac4e2e",
    "description": "Activity 2 asdfasfasdwegwge ago",
    "category": "drin134213ks",
    "date": "2019-10-15T21:39:01.7744925",
    "city": "Loneqwegdon",
    "venue": "Pwefwub"
}

###
PUT http://localhost:5000/api/activities/4641d21f-dcc8-4754-8f36-f1568a4648cb
Content-Type: application/json

{
    "title": "Past Activity"
}

###
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "email": "tom@test.com",
    "password": "Pa$$w0rd"
}

###
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "email": "tes33@",
    "password": "asdgewgwegewg",
    "displayName": "testest",
    "userName": "testesttset"
}

###
GET http://localhost:5000/api/profiles/tom
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJib2IiLCJuYmYiOjE1NzczMjQ4NTksImV4cCI6MTU3NzkyOTY1OSwiaWF0IjoxNTc3MzI0ODU5fQ.aHiFJ0Ok4nXGD-kJNRxJWJCvIlghk6dd_N4lw8sfQEboxbYKZGBqqjQCU1A3Q6MCVpcr6FWPj_mp3pFg0mYKlg

###
DELETE http://localhost:5000/api/photos/nbxgyf999tupypr219g1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJ0b20iLCJuYmYiOjE1Nzc1NTg4MTQsImV4cCI6MTU3ODE2MzYxNCwiaWF0IjoxNTc3NTU4ODE0fQ.wj3GrNwpae-T6vQSOF28G7RdEDkUKa676wiJTQ2kXZU35S0jLt1oy-kmsxR2U2LOMPKH34DYKX88gtFHpCquZQ

###
POST http://localhost:5000/api/photos/nbxgyf999tupypr219g1/setmain
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJ0b20iLCJuYmYiOjE1Nzc1NTg4MTQsImV4cCI6MTU3ODE2MzYxNCwiaWF0IjoxNTc3NTU4ODE0fQ.wj3GrNwpae-T6vQSOF28G7RdEDkUKa676wiJTQ2kXZU35S0jLt1oy-kmsxR2U2LOMPKH34DYKX88gtFHpCquZQ
